# Generated by Django 5.2.5 on 2025-09-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skillpost',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='matchrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skillpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skillpost',
            name='kind',
            field=models.CharField(choices=[('OFFER', 'Offer'), ('REQUEST', 'Request')], max_length=10),
        ),
    ]
